#!/usr/bin/bash

# This script loops over a list of cleaned input data and creates matching subdirectories.
# These folders will be used to hold our local .git working repositories.
# They are hosted at: https://github.com/learn-co-students/NAME_OF_DIRECTORY

# First, we declare our variables:
targetParentDir="/home/george/Documents/Flatiron/Learnco/"

# Then, we loop over our input file (passed as a command line argument) and create our folders:
while IFS= read -r line; do
    mkdir -p "$targetParentDir""$line"
    done < "$1"
